### ISSUE TITLE
We need a basic reference platform that isn't a 10k switch.

### ISSUE THREAD

**Issue by toganlabs** [NetworkGradeLinux/mion#1]
Katrina to look at QEMU

**Comment by johntoomey** [comment]
ordered 2x unbranded 8-port intel based switches from AliExpress to test as potential reference (development) platforms: https://www.aliexpress.com/snapshot/0.html?spm=a2g0s.9042647.6.2.4df64c4dAINBMj&orderId=8120016437449782&productId=4000777413889

**Comment by johntoomey** [comment]
we are going to use qemu for this rather than hardware
