### ISSUE TITLE
Barefoot SDE 9.4.0

### ISSUE THREAD

**Issue by toganlabs** [NetworkGradeLinux/mion#105]
APS requests that we upgrade to 9.4.0 of the barefoot SDE. @CommitThis and @Toganlabs have a branch and are currently testing.

**Comment by N-Mc-Nally** [comment]
@toganlabs hiya, this was moved to done, will you add details and we can close it?

**Comment by N-Mc-Nally** [comment]
@toganlabs hiya, this was moved to done, will you add details and we can close it?

**Comment by toganlabs** [comment]
Last commit in series here:

https://github.com/NetworkGradeLinux/meta-mion-sde/commit/a21cdca1c2b725ae7795fb446a1e8f212ca947f7

I've bumped it to 9.4.0 and tested with the 25G APSN switch with the 1.0.2 ref bsp.
