### ISSUE TITLE
2021.06 release blocking issues and tasks

### ISSUE THREAD

**Issue by johntoomey** [NetworkGradeLinux/mion#138]
- [x] Host contamination issue needs to be logged and moved to backlog - link to related issues @toganlabs https://github.com/NetworkGradeLinux/mion/issues/139
- [ ] Finalise release notes @johntoomey 

Testing - [doc](https://docs.google.com/spreadsheets/d/1ajP_V8e8Br2KMgCqQGceh9JOeGntOEEXv2eQW0JS7lc/edit#gid=1977743012) - [sheet](https://github.com/NetworkGradeLinux/mion-docs/wiki/Release-Test-plan)
- [x] Run tests on 6064 @CommitThis - done.
- [x] Run tests on TN48M @toganlabs 
- [x] Run tests on QEMU @kprosise 
- [x] Fix/update/remove the broken onlps tests @toganlabs - done.

The following issues need to be resolved:
- [ ] ~https://github.com/NetworkGradeLinux/meta-mion/issues/113~
- [x] https://github.com/NetworkGradeLinux/mion-docs/issues/202
- [x] https://github.com/NetworkGradeLinux/mion-docs/issues/204
- [x] https://github.com/NetworkGradeLinux/mion-docs/issues/219
- [x] https://github.com/NetworkGradeLinux/meta-mion-stratum/issues/3

Post release -
- [x] Review test plan and address open issues

**Comment by CommitThis** [comment]
I think we need to establish what the actual tests for ONLP should be. The [ONLP documentation on the internet ](http://opencomputeproject.github.io/OpenNetworkLinux/onlp/implementors/porting.html) does not make it at all clear whether or not the instructions are for ONLPv1 or ONLPv2.

As I stated in chat, the output of running `onlps` was the same, regardless of the test command run (as listed on aforementioned docs).

**Comment by johntoomey** [comment]
all items here have been addressed - closing
