### ISSUE TITLE
add CODE_OF_CONDUCT.md to the top level repo

### ISSUE THREAD

**Issue by johntoomey** [NetworkGradeLinux/mion#17]
https://docs.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project

**Comment by kprosise** [comment]
Please review the drafts for the code of conduct and our interpretation: https://github.com/NetworkGradeLinux/mion-docs/tree/dunfell/_drafts @benvantende @toganlabs

**Comment by kprosise** [comment]
Waiting on PR approval, after which this issue can be closed.
