### ISSUE TITLE
Add support for QEMU platform

### ISSUE THREAD

**Issue by kprosise** [NetworkGradeLinux/mion#22]

**Comment by N-Mc-Nally** [comment]
@kprosise and @toganlabs front-loading this for 2021.03 release.

**Comment by kprosise** [comment]
Qemu is building, however connecting to the instance has some potential issues to workout, and is going to require a bit of reading up on  qemu documentation.  See `meta-mion-bsp branch kprosise/add-qemu` for buildable qemu

**Comment by kprosise** [comment]
@toganlabs As we now have a qemu image that can be booted and can run the automated runtime and package tests, we need to figure out what the minimal requirements are in order to complete this task.  Specifically, (1)what ONLPV1 functions (such as onlpdump)  should run, and their desirable state, and (2) what hardware, if any, needs to be emulated.

**Comment by kprosise** [comment]
Output of onlps: 

```shell
/usr/bin/onlps
       System Information: = {
       Product Name: ONLSIM
       Part Number: ONL
       MAC: 00:00:00:00:00:00
   }

SFPs:
There are no SFP capable ports.
```
Is this something that we need to change/setup regarding emulation?

**Comment by kprosise** [comment]
Regarding onlpdump.py, there's an issue with the libonlp shared objects not being linked:

```shell
root@qemux86-64:/usr/bin# onlpdump.py 
Traceback (most recent call last):
  File "/usr/bin/onlpdump.py", line 13, in <module>
    import onlp.onlp
  File "/usr/lib/python2.7/onlp/onlp/__init__.py", line 8, in <module>
    libonlp = ctypes.cdll.LoadLibrary("libonlp.so")
  File "/usr/lib/python2.7/ctypes/__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libonlp.so: cannot open shared object file: No such file or directory
 ```
while this can be addressed within the image, I have yet to find out why this is not happening during  `do_install`. (see lines 262-275 of `onlpv1_1.0.bb`) I've already started to look into it, but advice is always welcome.

**Comment by kprosise** [comment]
Pending PR
