### ISSUE TITLE
Add ptest image type

### ISSUE THREAD

**Issue by toganlabs** [NetworkGradeLinux/mion#81]
We need an image that creates a ptest image.

**Comment by kprosise** [comment]
Update: To do things correctly, there was some minor issues I encountered while (a) running ptests set up in build/local.conf that I wanted to address and (b) the p-test image resulted in the tests not being included. 

I found the Yocto QA ptest image which I will be basing the mion one off of, which helps, and I hope to have this done in the near future.

**Comment by kprosise** [comment]
p-tests were not being included due to a "ptest" not being added to DISTRO_FEATURES. Can be added to local.conf. left out as Yocto does not permit it being added outside of such. 

Pull request has been opened.

**Comment by kprosise** [comment]
waiting on PR [meta-mion PR #96](https://github.com/NetworkGradeLinux/meta-mion/pull/96) approval. It's likely that this will require a bit of tweaking at some point however. @toganlabs

**Comment by kprosise** [comment]
Once mion #127 is merged, we can close this issue. Future changes can be done in later issues.

**Comment by kprosise** [comment]
Closing issue. The Ptest image will be visited again after the runtime testing image type is complete.
