### ISSUE TITLE
Define update strategy for all installation types

### ISSUE THREAD

**Issue by N-Mc-Nally** [NetworkGradeLinux/mion#90]

**Comment by johntoomey** [comment]
This needs to include out of tree kernel modules as mentioned here (issue closed as it is a duplicate of this): https://github.com/NetworkGradeLinux/mion/issues/93

**Comment by johntoomey** [comment]
started defining the document here: https://github.com/NetworkGradeLinux/mion-docs/wiki/Mion-update-strategy

**Comment by johntoomey** [comment]
this is as done as it can be - initial version of the strategy outlined above
- the tl;dr is that we will update the submodules weekly and users will need to build and install a new image using ONIE

next steps are to start looking at what needs to be done this release to set up the groundwork for updates using a package manager - details [here](https://github.com/NetworkGradeLinux/mion/issues/117) and meeting scheduled for monday the 26th of april
